- .github/workflows/deploy-main.yml
Resolves: #7
- #7 
- prisma 변경사항 적용 
- npm run start로 변경 
-
- prisma generate를 실행하여 Prisma Client 생성 
- 현재 배포 스크립트는 npm run start 실행을 기준으로 작성
> feat: Prisma 워크플로우 개선

- .github/workflows/deploy-main.yml
> Revert "feat: Prisma 워크플로우 개선"

- package-lock.json
- package.json
- swagger/schedule.swagger.yaml
Resolves: #10
- #10 
- 일정 화면 API에 대한 Swagger 문서 작성.
- API 엔드포인트 및 요청/응답 형식 정의.
- API 구현 시에 변경사항 발생하면, Swagger 문서도 함께 업데이트 예정.
> Feat: Swagger 작성 (SCHEDULE)

- config/jwt.middleware.js
- config/response.js
- package-lock.json
- package.json
- src/auth/auth.controller.js
- src/auth/auth.dto.js
- src/auth/auth.repository.js
- src/auth/auth.route.js
- src/auth/auth.service.js
- src/index.js
- src/utils/jwt.utils.js
- swagger/auth.swagger.yaml
- swagger/home.swagger.yaml
- 회원가입 API
- 토큰 추출 및 생성 함수 구현
- jwt middleware
- 스웨거 문서 수정
> Feat, docs : 회원가입 API, 토큰 추출 및 생성함수 구현, 스웨거 수정

- .http
- config/db.config.js
- src/index.js
- src/schedule/controllers/schedule.controller.js
- src/schedule/dto/auth.dto.js
- src/schedule/repositories/auth.repository.js
- src/schedule/routes/schedule.route.js
- src/schedule/services/schedule.service.js
여행 일정 목록 조회
지난 여행 목록 조회
즉흥 게시판 지역별 조회
현재 여행 일정 조회
저장된 미션 목록 조회
미션 인증하기
모든 미션이 일정 완료된 상태에서 여행 일정 조회
위 api 개발
> schedules 1순위 api

- src/home/home.controller.js
- src/home/home.dto.js
- src/home/home.repository.js
- src/home/home.service.js
- src/index.js
- swagger/home.swagger.yaml
* #16 - HOME 화면 관련 API
- 추후 인증 관련 수정
> [ FEATURE ] HOME 화면 관련 API

- .github/workflows/deploy-main.yml
Resolves: #25
- #25 
- GitHub Actions 워크플로우에 데이터베이스 관련 환경 변수를 추가했습니다.
- DB_HOST
- DB_USER
- DB_PASSWORD
> feat: GitHub Actions에 DB 관련 변수 추가

- src/auth/auth.controller.js
- src/auth/auth.repository.js
- src/auth/auth.service.js
- 회원가입시 이메일이 인증되었는지 검증하는 로직 추가
> refactor : 회원가입 로직 변경

- package-lock.json
- src/home/home.controller.js
- src/home/home.service.js
- src/index.js
> [ REFACTOR ] Home 관련 API jwt 인증 반영

- package-lock.json
- package.json
- src/index.js
- src/user/user.controller.js
- src/user/user.dto.js
- src/user/user.repository.js
- src/user/user.route.js
- src/user/user.service.js
- swagger/home.swagger.yaml
- swagger/user.swagger.yaml
* #29 - USER 관련 API
Closes #29
> [ FEATURE ] USER 관련 API

- src/home/home.dto.js
- src/home/home.repository.js
- swagger/home.swagger.yaml
* #32 - 랜덤 여행지 추출 방문 증감률 응답값 추가
> [ FEATURE ] 랜덤 여행지 추출 방문 증감률 응답값 추가

- src/home/home.controller.js
- src/home/home.dto.js
- src/home/home.service.js
- src/user/user.controller.js
- swagger/home.swagger.yaml
- swagger/user.swagger.yaml
* #34 - HOME, USER 관련 API 요청값 수정
> [ REFACTOR ] HOME, USER 관련 API 요청값 수정

- src/home/home.controller.js
- src/home/home.dto.js
- src/home/home.repository.js
- swagger/home.swagger.yaml
* #36 - 여행 날짜 응답값 형식 수정
* 등록 날짜 -1 오류 수정
> [ REFACTOR ] 여행 날짜 응답값 형식 수정

- src/user/user.controller.js
- src/user/user.dto.js
- src/user/user.repository.js
- src/user/user.route.js
- src/user/user.service.js
- swagger/home.swagger.yaml
- swagger/user.swagger.yaml
> [ FEATURE ] USER 화면 관련 API 추가 개발

- src/home/home.controller.js
- src/home/home.dto.js
- src/home/home.repository.js
- src/home/home.service.js
- src/index.js
- swagger/home.swagger.yaml
- swagger/user.swagger.yaml
> [ FEATURE ] HOME 화면 인기 미션 조회 API

- src/user/user.dto.js
- src/user/user.repository.js
- swagger/user.swagger.yaml
> [ FEATURE ] 미션 인증 사진 응답값 추가

- src/user/user.repository.js
> [ REFACTOR ] 게시글, 댓글 테이블명 수정

- src/home/home.controller.js
- src/home/home.repository.js
- src/home/home.service.js
- src/index.js
- src/user/user.controller.js
- src/user/user.repository.js
- src/user/user.route.js
- src/user/user.service.js
- swagger/home.swagger.yaml
- swagger/user.swagger.yaml
> [ FEATURE ] 여행 일정 관련 API 추가 개발

- src/index.js
> [ FIX ] 인기 미션 저장 API 라우터 추가

- src/user/user.repository.js
> [ FIX ] 사용자 프로필 조회 시 point 응답값 수정

- src/community/community.controller.js
- src/community/community.repository.js
- src/community/community.service.js
- swagger/community.swagger.yaml
DB에 맞춰 일정 화면 API 수정.
Resolves: #56
- #56 
- 변경된 DB 구조에 맞춰 일정 화면 API 수정.
- 수정된 API에 대한 Swagger 문서 업데이트.
> Feat: API 수정 및 Swagger 업데이트 (COMMUNITY)

- src/community/community.service.js
- swagger/community.swagger.yaml
Resolves: #58
- #58 
- 특정 게시물 조회에서 해당 post가 존재하는지 여부에 대한 코드 수정
> Fix: 특정 게시물 조회API 수정 (COMMUNITY)

- config/s3.js
- package-lock.json
- package.json
- src/home/home.route.js
- src/index.js
- src/user/user.controller.js
- src/user/user.dto.js
- src/user/user.repository.js
- src/user/user.route.js
- src/user/user.service.js
- swagger/user.swagger.yaml
> [ FEATURE ] 사용자 프로필 수정 API

- .github/workflows/deploy-main.yml
Resolves: #64
- #64 
- BUCKET_NAME, REGION, S3_KEYID, S3_PRIVATE_KEY, AUTO_CONTENT_TYPE 추가
> Feat: CICD에 S3 관련 변수 추가

- src/home/home.route.js
> [ FIX ] HOME API 라우터 수정

- src/community/community.controller.js
- src/community/community.dto.js
- src/community/community.repository.js
- src/community/community.route.js
- src/community/community.service.js
- swagger/community.swagger.yaml
- #61 
- `user_id`를 `req.body`가 아닌 `req`에서 받아오는 방식으로 코드 수정
- 토큰을 사용하여 게시글을 작성한 사용자가 아닌 접근을 차단할 수 있게 개선
- 수정된 내용에 기반하여 swagger 수정
> [ REFACTOR ] user_id를 토큰으로 변경

- src/community/community.controller.js
- src/community/community.repository.js
- src/community/community.route.js
- swagger/community.swagger.yaml
- #72 
- 인기게시판(total_comment, total_like, total_scrap) 변수 이름 변경
-  특정 게시글 조회에서 지역 정보 추가
-  token을 통해서 사용자의 좋아요 및 스크랩 여부 응답 추가
> fix: COMMUNITY 관련 API response 수정

- src/home/home.controller.js
- src/home/home.repository.js
- swagger/home.swagger.yaml
> [ REFACTOR ] 랜덤 여행지 추천 API 응답값 리팩토링

- src/community/community.repository.js
- swagger/community.swagger.yaml
- #84 
- 특정 게시물 조회 API 에서 response에 commend_id와 view_id 추가
> refactor: 특정 게시물 조회 API 응답 추가

- config/s3.js
- src/community/community.controller.js
- src/community/community.dto.js
- src/community/community.repository.js
- src/community/community.route.js
- src/community/community.service.js
- swagger/community.swagger.yaml
- #69 
- 커뮤니티 생성, 삭제, 수정에 대한 API에 S3 적용함
> Feat: 게시판 S3 적용 (COMMUNITY)

- config/s3.js
- src/community/community.controller.js
- swagger/community.swagger.yaml
- #90 
- S3와 관련된 API (사진 업로드, 사진 삭제) 에서의 응답값 수정
> refactor: s3관련 API 응답 수정

- config/s3.js
- src/community/community.controller.js
- #95 
- files이 undefined일시 서버 crash 방지를 위한 에러 핸들러 수정
> refactor: S3 사진 업로드 API 에러 핸들러 수정

- src/community/community.controller.js
- swagger/community.swagger.yaml
- #99 
- 사진이 없을 때에도 게시글 작성이 되도록 함 
- 사진을 request body에 안넣으면 [] 빈 배열로 들어가게 함
> refactor: 게시글 작성 API 수정

- src/community/community.controller.js
- src/community/community.route.js
- swagger/community.swagger.yaml
- #102 
- 전체 게시글 조회 시 viewer의 공감 및 스크랩 여부 응답 추가
> refactor: 전체 게시글 조회 API 응답 수정

- src/schedule/repositories/auth.repository.js
- src/schedule/services/schedule.service.js
> Feature schedule api

- src/schedule/repositories/auth.repository.js
> fix: 특정  일정 조회 수정

- src/schedule/repositories/auth.repository.js
- src/schedule/services/schedule.service.js
> fix: 미션 조회

- src/community/community.controller.js
- src/community/community.route.js
- swagger/community.swagger.yaml
- #108 
- viewer의 공감 및 스크랩 여부에 대한 응답 추가
> refactor: 인기 게시판 조회 API 응답 수정

- src/home/home.controller.js
- src/home/home.dto.js
- src/home/home.repository.js
- src/home/home.service.js
- swagger/home.swagger.yaml
- #110 
- 인기 미션 조회시 사용자의 미션 저장 여부 응답 추가
> refactor: 인기미션 조회 API 응답 수정
